### ISSUE TITLE
Interactive code snippets

### ISSUE THREAD

**Issue by viebel** [clojure-doc/clojure-doc.github.io#12]
I’d like to discuss with you guys about the idea of integrating Klipse in order to feature interactive code snippets in clojure-doc.github.io

**Comment by seancorfield** [comment]
Sounds like a cool idea. Is it something you'd be willing to create a PR for (across the **source** branch) or is it something that needs discussion first?

**Comment by viebel** [comment]
I could create a PR if you tell me that you are interested.

**Comment by viebel** [comment]
Here is a PR with an example of an article featuring interactive code snippets https://github.com/clojure-doc/clojure-doc.github.io/pull/13

**Comment by seancorfield** [comment]
https://clojure-doc.github.io/articles/language/laziness/ -- very nice!

I assume the only caveat is that only ClojureScript-compatible code can be handled like this so contributors need to be careful in the future about that?

I will note that `random-uuid` in your PR is only available in Clojure 1.11 Alpha 3 and it requires the Java interop in earlier versions (I'm about to edit that page to show both, with the Java interop version being non-interactive).

**Comment by seancorfield** [comment]
I've made about half of the introduction interactive as well now. Thanks for the prompt.
