### ISSUE TITLE
Invalid Link (404) on Getting Started > Starting Clojure screencast

### ISSUE THREAD

**Issue by EMPAT94** [clojure-doc/clojure-doc.github.io#21]
On page https://clojure-doc.org/articles/tutorials/getting_started/

Under section "**See Also**"

The url for "Starting Clojure screencast" http://cemerick.com/2012/05/02/starting-clojure/ is no longer accessible.

**Comment by seancorfield** [comment]
Thank you! Fixed. Should be published soon.
