### ISSUE TITLE
Links and inline code elements use the same styling and that's confusing

### ISSUE THREAD

**Issue by phronmophobic** [clojure-doc/clojure-doc.github.io#49]
Please refer to my terrible diagram.

![confusing-formatting](https://github.com/clojure-doc/clojure-doc.github.io/assets/156241/2edd7932-b721-4b70-9861-edc429a5740d)

**Comment by seancorfield** [comment]
Yeah, I've been meaning to change that part of the Cryogen theme for ages -- thanks for the "prod" 😸
