### ISSUE TITLE
Better contributor guideline for audience level?

### ISSUE THREAD

**Issue by seancorfield** [clojure-doc/clojure-doc.github.io#52]
Language should be basic but clear reference material?

Tutorials should be step-by-step introductory material?

Cookbooks should be able to assume relevant Language and Tutorials have been covered and should build on that?

**Comment by bobisageek** [comment]
I think <https://github.com/clojure-doc/clojure-doc.github.io#structure> touches on this for some categories, and is probably good info for both contributors and consumers. Contributors have guidelines of how to target/format content, and consumers can self-define what level they're at and what they're looking for.

**Comment by seancorfield** [comment]
Having looked over this, I agree that it is sufficient detail -- until someone offers PRs to improve it at some point.
