### ISSUE TITLE
Basic-web tutorial: ring-core of "1.11.0" version causes an SLF4J warnings

### ISSUE THREAD

**Issue by catwhosad** [clojure-doc/clojure-doc.github.io#70]
Hi.
Not sure if this is a "real" issue, but when I'm trying to follow ["Basic web" tutorial ](https://clojure-doc.org/articles/tutorials/basic_web_development/#create-and-set-up-your-project) and when I update all dependencies in `deps.edn` to current versions, I receive such warning:
```
> clojure -M -m basic-web.handler
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
But web server runs, I can open `localhost:3000` in browser and it works as expected.
Still I don't receive any other information inside console, just that warning.

After trying different things I found that this happens when I use `1.11.0` version of `ring-core` and `ring-jetty-adapter`.
Even with `1.10.0` version everything works as expected.

To fix this and make it work we need to add `org.slf4j/slf4j-simple {:mvn/version "2.0.11"}`(current version) as additional dependency inside `deps.edn`.
After that we'll see expected info messages and no warnings:
```
> clojure -M -m basic-web.handler
[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.18; built: 2023-10-27T02:14:36.036Z; git: 5a9a771a9fbcb9d36993630850f612581b78c13f; jvm 21.0.2+13-LTS
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@1f207142{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@76ebd595{HTTP/1.1, (http/1.1)}{0.0.0.0:3000}
[main] INFO org.eclipse.jetty.server.Server - Started Server@74ed7111{STARTING}[11.0.18,sto=0] @3017ms
```
Not sure if this is a correct solution, but I think it should be mentioned somewhere that we shouldn't change versions or information how to fix this in correct way should be added.

P.S.: Every other dependencies were updated to current versions, but only `release` ones without alpha/beta/etc.

**Comment by seancorfield** [comment]
Thanks for the heads up! That page was updated last year to all the latest versions available at the time and you can never predict what later versions of Java dependencies might do to the project.

I'll make a pass over the tutorial soon to update all the deps and retest everything and either add the simple SLF4J dep or explain what the warnings mean. Logging in Java is a giant hot mess, unfortunately. Maybe I should add a logging cookbook? 😄
